name: Build, Push and Deploy

on:
  push:
    branches:
      - VPS-version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build static files
        run: npm install && npm run build
      - name: Archive static files
        run: tar -czvf build.tar.gz -C dist/ .
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: temp
      - name: Copy and deploy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "temp/build.tar.gz"
          target: "~/"
      - name: Extract files on server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/home/* && tar --no-same-permissions --no-overwrite-dir -xzvf ~/temp/build.tar.gz -C /var/www/home && rm ~/temp/build.tar.gz
